// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseApplication.Models.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 30.0m,
                            Category = "食",
                            Date = new DateTime(2024, 7, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "豆干"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 30.0m,
                            Category = "食",
                            Date = new DateTime(2023, 7, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "燙青菜"
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 100.0m,
                            Category = "食",
                            Date = new DateTime(2024, 7, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "紅燒肉"
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 999.0m,
                            Category = "衣",
                            Date = new DateTime(2024, 7, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "米色小外套"
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 199.0m,
                            Category = "食",
                            Date = new DateTime(2024, 7, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "節瓜"
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 120.0m,
                            Category = "行",
                            Date = new DateTime(2024, 7, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "IRent租車"
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 12000.0m,
                            Category = "住",
                            Date = new DateTime(2024, 7, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "房租"
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 1200.0m,
                            Category = "住",
                            Date = new DateTime(2024, 7, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "電費"
                        },
                        new
                        {
                            Id = 9L,
                            Amount = 205.0m,
                            Category = "住",
                            Date = new DateTime(2024, 7, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "水費"
                        },
                        new
                        {
                            Id = 10L,
                            Amount = 300.0m,
                            Category = "住",
                            Date = new DateTime(2024, 7, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "瓦斯費"
                        },
                        new
                        {
                            Id = 11L,
                            Amount = 500.0m,
                            Category = "住",
                            Date = new DateTime(2024, 7, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "網路費"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
